#!/usr/bin/python

import argparse
import sys
import re
import cgi

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--paragraphs', action='store_true')
    args = parser.parse_args()

    data = sys.stdin.read()
    if args.paragraphs:
        for p in re.split(r'\n{2,}', data.strip('\n')):
            print '<p>' + cgi.escape(p).replace('\n', '<br>\n')
    else:
        sys.stdout.write(cgi.escape(data))
