#!/bin/sh

set_color() {

    case $1 in
        black)          FG=30;;
        red)            FG=31;;
        green)          FG=32;;
        yellow)         FG=33;;
        blue)           FG=34;;
        magenta)        FG=35;;
        cyan)           FG=36;;
        white|*)        FG=37;;
    esac

    case $2 in
        red)            BG=41;;
        green)          BG=42;;
        yellow)         BG=43;;
        blue)           BG=44;;
        magenta)        BG=45;;
        cyan)           BG=46;;
        white)          BG=47;;
        black|*)        BG=40;;
    esac

    case $3 in
        bold)           AT=01;;
        underscore)     AT=02;;
        blink)          AT=03;;
        reverse)        AT=04;;
        concealed)      AT=05;;
        none|*)         AT=00;;
    esac

    echo -ne "\033[${AT};${BG};${FG}m"
}

reset_color () {
    echo -ne "\033[0m"
}

for at in none bold blink; do
    for bg in black red green yellow blue magenta cyan white; do
        for fg in black red green yellow blue magenta cyan white; do
            set_color $fg $bg $at
            echo -n " $fg "
            reset_color
        done
        echo
    done
done
