#!/usr/bin/python

import sys
import re
import gtk

poundcolor = re.compile('#[0-9a-fA-F]+')
selcolor = None

def pick_color(name):
    sel = gtk.ColorSelectionDialog('Pick a color')
    sel.colorsel.set_current_color(gtk.gdk.color_parse(name))

    def ok(widget):
        global selcolor
        selcolor = sel.colorsel.get_current_color().to_string()

    sel.ok_button.connect('clicked', ok)
    sel.ok_button.connect('clicked', gtk.main_quit)
    sel.cancel_button.connect('clicked', gtk.main_quit)

    sel.show()
    gtk.main()
    sel.hide()

    return selcolor

if __name__ == '__main__':
    if len(sys.argv) > 1:
        for name in sys.argv[1:]:
            print pick_color(name)
    else:
        for line in sys.stdin:
            print poundcolor.sub(lambda m: pick_color(m.group(0)), line),
