#!/usr/bin/env ruby

$cols = (ENV['COLUMNS'] || `tput cols`.chomp).to_i

def show(n)
  "#{n} #{dots(n, n.to_s.length + 1, $cols)}"
end
def dots(n, h, cols)
  avail = cols - (h + n / cols)
  chunks = n / avail
  remain = n % avail
  '#' * chunks + '.' * remain
end
def clear(n)
  "\r#{' ' * show(n).size}\r"
end
def skew(target)
  Time.now.to_f - target
end

ARGV.map(&:to_i).each do |delay|
  begin
    finish = Time.now.to_f + delay
    delay.downto(1) do |n|
      print show(n)
      sleep 1 - skew(finish - n)
      print clear(n)
    end
  rescue Interrupt
    STDERR.puts "canceled with #{(finish - Time.now.to_f).round(1)}s left"
  end
end
