#!/usr/bin/env ruby

def show(n)
  "#{n} #{'.' * n}"
end
def clear(n)
  "\r#{' ' * show(n).size}\r"
end
def skew(target)
  Time.now.to_f - target
end

ARGV.map(&:to_i).each do |delay|
  finish = Time.now.to_f + delay
  delay.downto(1) do |n|
    print show(n)
    begin
      sleep 1 - skew(finish - n)
    rescue Interrupt
      puts
      exit
    end
    print clear(n)
  end
end
