#!/bin/sh

FONT='-*-lucida-medium-r-*-sans-12-*-*-*-*-*-iso10646-1'
COLOR='-nb honeydew2 -nf black -sb honeydew4 -sf white'

dm() {
    dmenu $COLOR -fn $FONT
}

lx() {
    IFS=':'; lsx $PATH
}

case $1 in
    --edit)
        while d="$(ls -ap | sort -d | dm)" && test "$d"; do
            if [ -d "$d" ]; then
                cd "$d"
            else
                exec x-terminal-emulator -e sensible-editor "$d"
            fi
        done
        ;;
    --run|*)
        exec "$(lx | sort | dm)"
        ;;
esac
