#!/bin/sh

# In case we haven't fixed sudo to preserve this env var, need
# to be able to find our socket
test -z "$TMPDIR" -a -e "$HOME/tmp" && export TMPDIR="$HOME/tmp"

# For emacsclient, we always want to create a frame; if we fall
# back to a new emacs, we only need the option on a tty
test -t 0 && tty=-nw

emacsclient "${tty:--c}" -a false "$@" || emacs ${tty:+-nw} "$@"
