#!/bin/sh

test -t 0 && tty='-t'
test -n "$*" || set -- -e nil

# Work around sudo braindamage
test -z "$TMPDIR" -a -d "$HOME/tmp" && export TMPDIR="$HOME/tmp"

exec emacsclient "${tty:--c}" -a "" "$@"
