#!/bin/sh

test -t 0 && tty='-t'
test -n "$*" || set -- -e nil

# sudo likes to clear the environment
test -z "$TMPDIR" -a -e "$HOME/tmp" && export TMPDIR="$HOME/tmp"

exec emacsclient "${tty:--c}" -a "" "$@"
