#!/usr/bin/env ruby

class Eta
  UNITS = {d: 86400, h: 3600, m: 60, s: 1}
  ALPHA = 0.2
  def initialize(goal, verbose)
    @goal = goal
    @verbose = verbose
  end
  def update(x, t=Time.now.to_f)
    return 'no input' if x.nil?
    return 'stalled' if x == @prev_x
    return 'done' if x == @goal
    if @prev_x
      int = (t - @prev_t) / (x - @prev_x)
      @avg_int = @avg_int ? (1 - ALPHA) * @avg_int + ALPHA * int : int
      eta = (@goal - x) * @avg_int
    end
    @prev_x = x
    @prev_t = t
    return 'initializing' if @avg_int.nil?
    return 'divergent' if eta < 0
    return '%s avg %s cur %s' % [detail(eta), rate(@avg_int), rate(int)]
  end
  def detail(t)
    (@verbose ? "at #{abs_time(0)} " : '') + "eta #{abs_time(t)} (#{rel_time(t)})"
  end
  def abs_time(t)
    (Time.now + t).strftime(t > UNITS[:d] ? '%FT%X' : '%X')
  end
  def rel_time(t)
    UNITS.map {|u, s| r, t = t.divmod(s); "#{r}#{u}" if r > 0 || u == 's' }.compact.join
  end
  def rate(int)
    UNITS.map {|u, s| '%.1f/%s' % [s/int, u] if int.abs < s }.compact.last
  end
end

begin
  eta = Eta.new(ARGV.first.to_f, ENV['VERBOSE'])
  STDIN.each_line do |line|
    puts "#{line.chomp}\t#{eta.update(line =~ /[\d.-]+/ ? $&.to_f : nil)}"
  end
rescue Interrupt
end
