#!/usr/bin/python

import sys
import gtk

if __name__ == '__main__':
    sel = gtk.FontSelectionDialog('fontsplat')
    try:
        sel.fontsel.set_font_name(sys.argv[1])
    except IndexError:
        pass

    def print_font(w):
        gtk.rc_parse_string('gtk_font_name = "%s"' %
                            sel.fontsel.get_font_name())

    sel.connect('destroy', gtk.main_quit)
    sel.ok_button.connect('clicked', print_font)
    sel.cancel_button.connect('clicked', gtk.main_quit)

    sel.fontsel.set_size_request(600, 400)
    sel.show()
    gtk.main()
