#!/usr/bin/perl -w

use Math::Trig qw(deg2rad great_circle_distance);

sub d2r { deg2rad($_[1]), deg2rad(90 - $_[0]) }

print great_circle_distance(d2r($ARGV[0], $ARGV[1]),
                            d2r($ARGV[2], $ARGV[3]), 6378), " km\n";
