#!/bin/sh

command -v md5 >/dev/null 2>&1 || md5() { md5sum "$@"|cut -d' ' -f1; }
if date --help >/dev/null 2>&1; then y='-d -1day'; else y='-v -1d'; fi
d=$(date $([ $2 -gt -30 ]&&echo $y) +%F);dji=$(GET xrl.us/djiopen|col)
(echo 16i;echo -n "$d-$dji"|md5|sed 's/.\{16\}/0.&p/g'|tr a-f A-F)|dc\
|while read x; do echo $1$x; shift; done
