#!/usr/bin/ruby

require 'rubygems'
require 'sinatra'

def read_list(path)
  File.open(path).read.split("\n") rescue []
end

def save_list(path, items)
  File.open(path, 'w') {|fp| fp.write(items.join("\n")) }
end

before do
  halt 401, 'Forbidden' unless request.path_info =~ /^\/[\w.-]*$/
end

get '/' do
  erb :index
end

get '/:list' do
  @items = read_list(params[:list])
  erb :list
end

put '/:list' do
  save_list(params[:list], request.body.read.split("\n"))
  redirect request.url, 303
end

post '/:list' do
  @items = read_list(params[:list]) - params[:del].to_a + params[:add].to_a
  save_list(params[:list], @items)
  erb :list
end

__END__

@@ layout
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Groceries</title>
<%= yield %>

@@ index
<p>To make a list, <a href="<%= request.url %>mylist">just choose a name</a>,
or upload it with HTTP PUT: <code>curl -T mylist <%= request.url %></code>

@@ list
<form method="post"><% @items.each do |i| %>
  <input type="checkbox" name="del" value="<%= i %>"><%= i %><br><% end %>
<p><input type="text" name="add">
<p><input type="submit" value="Add/Remove">
</form>
