#!/usr/bin/ruby

require 'rubygems'
require 'sinatra'

class List
  def initialize(path); @path = path; end
  def load; File.open(@path).read.split($/) rescue []; end
  def save(items); File.open(@path, 'w') {|f| f.puts(items.join($/)) }; end
end

before do
  halt 401, 'Forbidden' unless request.path_info =~ /^\/[\w.-]*$/
end

get '/' do
  erb :welcome
end

put '/' do
  redirect request.url + params[:list], 303
end

get '/:list' do
  @items = List.new(params[:list]).load
  erb :tickyboxes
end

put '/:list' do
  List.new(params[:list]).save(request.body.read.split($/))
  redirect request.url, 303
end

post '/:list' do
  list = List.new(params[:list])
  list.save(list.load - params[:del].to_a + params[:add].to_a)
  redirect request.url, 303
end

__END__

@@ layout
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Groceries</title>
<%= yield %>

@@ welcome
<form method="post"><input type="hidden" name="_method" value="put">
<p>Make a list: <input type="text" name="list"> <input type="submit"></form>
<p>Or upload one: <code>curl -T list <%= request.url %></code>

@@ tickyboxes
<form method="post"><% @items.each do |i| %>
  <input type="checkbox" name="del" value="<%= i %>"><%= i %><br><% end %>
<p><input type="text" name="add">
<p><input type="submit" value="Add/Remove">
</form>
