#!/usr/bin/python

import sys

def print_hist(data, buckets=20, bsize=None, cols=68):
    lo = min(data)
    hi = max(data)
    if bsize:
        buckets = (hi - lo) / bsize
        lo -= lo % bsize
    else:
        bsize = (hi - lo) / buckets

    b = {}
    for x in data:
        n = int((x - lo) / bsize)
        b[n] = b.setdefault(n, 0) + 1

    mode = max(b.values())
    for n in range(0, buckets):
        print '%4d' % (lo + n * bsize), '#' * (cols * b.get(n, 0) / mode)

if __name__ == '__main__':
    try:
        data = [int(line) for line in sys.stdin]
        args = [int(a) for a in sys.argv[1:]]
    except ValueError:
        sys.exit(1)

    print_hist(data, *args)
