#!/usr/bin/python

import sys
import Levenshtein as lev

if __name__ == '__main__':
    try:
        search = int(sys.argv[1])
        cutoff = int(sys.argv[2])
    except IndexError:
        search = 800
        cutoff = 6

    history = [line.rstrip('\n') for line in sys.stdin.readlines()]
    pruned = []
    seen = {}

    for line in reversed(history):
        if line in seen:
            continue
        else:
            seen[line] = True
        for goodline in pruned[-search:]:
            if lev.distance(line, goodline) < cutoff:
                break
        else:
            pruned.insert(0, line)

    print '\n'.join(pruned)
