#!/usr/bin/python

import sys
import Levenshtein as lev

if __name__ == '__main__':
    try:
        search = int(sys.argv[1])
        cutoff = int(sys.argv[2])
    except IndexError:
        search = 10
        cutoff = 4

    lines = sys.stdin.readlines()
    out = []

    for ln in reversed(lines):
        for goodln in out[-search:]:
            if lev.distance(ln, goodln) < cutoff:
                break
        else:
            out.insert(0, ln.rstrip('\n'))

    print '\n'.join(out)
