#!/usr/bin/python

import sys
import Levenshtein as lev

if __name__ == '__main__':
    try:
        search = int(sys.argv[1])
        cutoff = int(sys.argv[2])
    except IndexError:
        search = 10
        cutoff = 4

    lines = sys.stdin.readlines()
    print lines[0],

    for i in range(1, len(lines)):
        for j in range(max(0, i - search), i):
            if lev.distance(lines[i], lines[j]) < cutoff:
                break
        else:
            print lines[i],
