#!/usr/bin/perl

use Getopt::Std;
getopts('io:', \%opts);

$magic = "\xab\xcd";
$delim = "\xff";

if ($opts{i}) {
    local $/ = undef;
    $blob = <>;
    die "no magic" if substr($blob, 0, 2, "") ne $magic;
    while ($blob =~ s/^$delim.{4}(.*?)\x00//ms) {
        print "$1\n";
    }
} elsif ($opts{o}) {
    # we are most likely in a pipe:
    # khist -i .sh_history | stuff ... | khist -o .sh_history
    # so wait for input before overwriting the given file.
    vec($rin, fileno(STDIN), 1) = 1;
    select($rin, undef, undef, undef);

    open STDOUT, ">$opts{o}" unless $opts{o} eq "-";
    print $magic;
    while (<>) {
        chomp;
        print $delim, pack("NZ*", ++$i, $_);
    }
}
