#!/bin/sh

timer=$1; shift
msg="$*"
guess=72
pad=50
width=$(($(xdpyinfo | sed -n 's/dimensions: *\([0-9]*\)x.*/\1/p') - $pad))
tmp=$(mktemp)

pango-view --margin $pad --font "Sans $guess" -t "$msg" -q -o $tmp
sleep $timer

try=$(file $tmp | sed -n 's/.* PNG image, \([0-9]*\) x.*/\1/p' && rm $tmp)
adj=$(echo "6k $width $pad 2 * - $try $pad 2 * - / $guess * p" | dc)

pango-view --margin $pad --font "Sans ${adj}" -t "$msg" #-q -o $tmp
