#!/usr/bin/perl

use Getopt::Std;
getopts('ios', \%opts);

$magic = "\xab\xcd";
$delim = "\xff";

if ($opts{i}) {
    local $/ = undef;
    $blob = <>;
    die "no magic" if substr($blob, 0, 2, "") ne $magic;
    while ($blob =~ s/^$delim(.{4,}?\x00)//s) {
        ($n, $cmd) = unpack("NZ*", $1);
        $cmds{$n} = $cmd;
    }
    if ($opts{s}) {
        $seen{$cmds{$_}} = $_ for sort {$a<=>$b} keys %cmds;
        print ++$i."\t$_\n" for sort {$seen{$a}<=>$seen{$b}} keys %seen;
    } else {
        print "$_\t$cmds{$_}\n" for sort {$a<=>$b} keys %cmds;
    }
} elsif ($opts{o}) {
    print $magic;
    while (<>) {
        chomp; ($n, $cmd) = split(/\t/, $_, 2);
        print $delim, pack("NZ*", $n, $cmd);
    }
}
