#!/usr/bin/perl

use Getopt::Std;
getopts('io', \%opts);

$magic = "\xab\xcd";
$delim = "\xff";

if ($opts{i}) {
    local $/ = undef;
    $blob = <>;
    die "no magic" if substr($blob, 0, 2, "") ne $magic;
    while ($blob =~ s/^\xff.{4}(.*?)\x00//ms) {
        print "$1\n";
    }
} elsif ($opts{o}) {
    print $magic;
    while (<>) {
        chomp;
        print $delim, pack("NZ*", ++$i, $_);
    }
}
