#!/bin/sh

state=$HOME/var/lk
banner=http://www.kernel.org/kdist/finger_banner
tree=2.6
flavors='stable prepatch'
temp=`mktemp` || exit 1

curl -s $banner | grep "$tree" > $temp

for i in $flavors; do
    awk "/latest $i/{print\"$i:\",\$NF;exit}" $temp | confer -i $state/$i
done

rm -f $temp
