#!/bin/sh

state_dir=$HOME/var/lk
creds=$HOME/lib/lk/creds
banner_url=http://www.kernel.org/kdist/finger_banner
twitter_url=http://api.twitter.com/1/statuses/update.xml
tree=2.6
flavors='stable mainline'
temp=`mktemp` || exit 1

curl -s $banner_url | grep "$tree" > $temp

for i in $flavors; do
    x="$(awk "/latest $i/{print\"$i:\",\$NF;exit}" $temp \
        | confer -i $state_dir/$i)"
    if [ "$x" ]; then
        curlicue -f $creds -- \
            -s -d "status=$(urlencode "$x")" "$twitter_url" >/dev/null
    fi
done

rm -f $temp
