#!/bin/sh

n=$(mpc playlist | wc -l)

if [ "$*" = "-" ]; then
    while read line; do eval "mpc search $line"; done
else
    mpc search "$@"
fi | \
    vipe | mpc add | grep -q . && mpc play $(($n+1))
