#!/bin/sh

do_search() {
    if [ "$*" = "-" ]; then
        while read line; do mpc search any "$line"; done
    else
        mpc search any "$@"
    fi
}

n=$(mpc playlist | wc -l)

if do_search "$@" | vipe | mpc add; then
    mpc play $(($n+1))
fi
