#!/bin/sh -e

# Suggested usage: either from cron on Monday morning (for always-on
# systems), or in shell init (for laptops etc).

link=${1:-~/mess}
unfiled_relative_to_link=${2:-unfiled}
week=$(date +%Y-W%V)
target=$unfiled_relative_to_link/$week

if test "$(readlink "$link")" != "$target"; then
    echo "Welcome to week $week! creating scratch dir and updating link:"
    mkdir -p "$target"
    ln -sfn "$target" "$link"
    ls -l "$link"
fi
