#!/usr/bin/python

import sys
import getopt
import pymetar

if __name__ == '__main__':
    opts, args = getopt.getopt(sys.argv[1:], 'v')

    verbose = False
    for opt, arg in opts:
        if opt == '-v':
            verbose = True

    try:
        station = args[0]
    except IndexError:
        station = 'KBOS'

    f = pymetar.ReportFetcher(station)
    p = pymetar.ReportParser()
    r = p.ParseReport(f.FetchReport())

    if not verbose:
        print r.getWeather(), '(%s C)' % r.getTemperatureCelsius()

    else:
        head = '%s; %s' % (r.getStationCity(), r.getISOTime())
        print head; print '=' * len(head)

        obs = []
        obs.append(('Conditions', r.getWeather()))
        obs.append(('Temperature', r.getTemperatureCelsius()))
        obs.append(('Wind', '%s %s m/s' %
                            (r.getWindCompass(), r.getWindSpeed())))
        obs.append(('Visibility', '%s km' % r.getVisibilityKilometers()))
        obs.append(('Dew Point', '%s' % r.getDewPointCelsius()))
        obs.append(('Humidity', '%s%%' % r.getHumidity()))

        width = max([len(o[0]) for o in obs]) + 2
        for o in obs:
            print '%*s: %s' % (width, o[0], o[1])
