#!/usr/bin/python

import sys
import getopt
import pymetar

if __name__ == '__main__':
    opts, args = getopt.getopt(sys.argv[1:], 'v')

    verbose = False
    for opt, arg in opts:
        if opt == '-v':
            verbose = True

    try:
        station = args[0]
    except IndexError:
        station = 'KBOS'

    f = pymetar.ReportFetcher(station)
    p = pymetar.ReportParser()
    r = p.ParseReport(f.FetchReport())

    if not verbose:
        print r.getWeather(), '(%s C)' % r.getTemperatureCelsius()

    else:
        head = '%s; %s' % (r.getStationCity(), r.getISOTime())
        print head; print '=' * len(head)

        print 'Conditions: %s, %s' % (r.getWeather(), r.getSkyConditions())
        print 'Temperature: %s C' % r.getTemperatureCelsius()
        print 'Wind: %s, %s m/s' % (r.getWindCompass(), r.getWindSpeed())
        print 'Visibility: %s km' % r.getVisibilityKilometers()
        print 'Dew Point: %s C' % r.getDewPointCelsius()
        print 'Relative Humidity: %s%%' % r.getHumidity()
