#!/bin/sh

delta="$1"
tick="${2:-1}"

curvol() {
    mpc volume | sed 's/^volume:  *\([0-9]*\)%.*/\1/'
}

case "$delta" in
    -)
        step='-1'; n="$(curvol)";;
    -*)
        step='-1'; n="${1##-}";;
    +*)
        step='+1'; n="${1##+}";;
    *)
        echo 'usage: mfade {+N|-N|-} [SEC]'; exit 2;;
esac

if [ "$(curvol)" = 0 ]; then
    mpc play
fi

for i in $(seq "$n"); do
    mpc --quiet volume "$step"
    printf "fading: $(curvol)%% "
    sleep "$tick"
    printf '\r'
done

if [ "$(curvol)" = 0 ]; then
    mpc pause
else
    mpc
fi
