#!/bin/sh

mpd_root=$(sed -n 's/^[[:space:]]*music_directory[[:space:]]*"\?\([^"]*\)\"\?/\1/p' /etc/mpd.conf)
real_root=$(readlink -f "$mpd_root")

for i; do
    path="$(readlink -f "$i")"
    echo "${path##$real_root/}"
done
