#!/bin/sh

SCRIPT='s/^[[:space:]]*music_directory[[:space:]]*"\?\([^"]*\)\"\?/\1/p'
ROOT=$(cd "$(sed -n "$SCRIPT" /etc/mpd.conf)" && pwd -P)

for i in "$@"; do
    path=$(cd "$i" && pwd -P)
    echo "${path##$ROOT/}"
done
