#!/usr/bin/env ruby

require 'optparse'
require 'nokogiri'

attr = nil
markdown = true
strip = false

OptionParser.new do |op|
  op.on('-a ATTR') {|a| attr = a }
  op.on('-t') { markdown = false }
  op.on('-s') { strip = true }
end.parse!

if markdown
  begin
    require 'reverse_markdown'
  rescue LoadError
    STDERR.puts 'could not load reverse_markdown, disabling'
    markdown = false
  end
end

doc = Nokogiri::HTML(STDIN.read)
ARGV.each do |sel|
  doc.css(sel).each do |elt|
    text = attr ? elt[attr] : markdown ? ReverseMarkdown.convert(elt) : elt.text
    puts strip ? text.strip : text
  end
end
