#!/bin/bash

# This runs from cron every morning and mirrors my repos. While it's at
# it, it checks the date on each HEAD and wakes me up with a card from
# the Oblique Strategies deck if I haven't committed to anything in some
# number of days (and therefore probably need some inspiration).

repos_dir=~/pub/git
fortune_dir=~/lib/oblique
mail_subj='oblique strategy'
mail_dest='mobile'

grace='30' # days
delay='4' # hours

age="$(($(date +%s) - $grace * 86400))"
tmp="$(mktemp)"

for repo in "$repos_dir"/*.git; do
    test -t 1 && echo "Mirroring $repo"
    (cd "$repo" &&
        git log -1 --pretty=tformat:%at >> "$tmp" &&
        for r in $(git remote); do
            git push "$r" 2>&1 | grep -v 'Everything up-to-date'
        done)
done

if test "$(sort -n "$tmp" | tail -1)" -le "$age"; then
    sched -d "${delay}h" fortune "$fortune_dir" | mail -s "$mail_subj" "$mail_dest"
fi

rm -f "$tmp"
