#!/usr/bin/env ruby

require 'time'
require 'optparse'
require 'ostruct'

def parse_args(&blk)
  OpenStruct.new.tap do |o|
    OptionParser.new.instance_exec(o, &blk).parse!
  end
end

options = parse_args do |opts|
  opts.mode = :iso
  on('-i', '--iso') { opts.mode = :iso }
  on('-f', '--format F') {|arg| opts.mode = :format; opts.format = arg }
  on('-m', '--minutes') { opts.mode = :diff; opts.unit = 60 }
  on('-h', '--hours') { opts.mode = :diff; opts.unit = 3600 }
  on('-d', '--days') { opts.mode = :diff; opts.unit = 86400 }
  on('-o', '--round R') {|arg| opts.round = arg }
  on('-p', '--posix') { opts.mode = :format; opts.format = '%Y%m%d%H%M.%S' }
  on('-r', '--reference') { opts.reference = true }
  on('-v', '--verbose') { opts.verbose = true }
end

def try_clf(d)
  Time.strptime(d, '%d/%b/%Y:%H:%M:%S %z')
rescue ArgumentError
  nil
end

def try_chronic(d)
  require 'chronic'
  Chronic.parse(d)
rescue LoadError
  nil
end

def try_generic(d)
  Time.parse(d)
rescue ArgumentError
  nil
end

def parse_time(d)
  try_clf(d) || try_chronic(d) || try_generic(d)
end

ARGV.each do |arg|
  t = options.reference ? File.mtime(arg) : parse_time(arg)
  if t
    s = case options.mode
    when :iso
      t.iso8601
    when :format
      t.strftime(options.format)
    when :diff
      diff = ((Time.now - t) / options.unit.to_f).abs
      case options.round
      when 'down', 'floor'
        diff.floor
      when 'up', 'ceil'
        diff.ceil
      else
        diff.round(options.round.to_i)
      end
    end
    s += "\t#{arg}" if options.verbose
    puts s
  else
    STDERR.puts 'All parsing methods failed'
    puts arg
  end
end
