#!/bin/sh

name_and_size() {
    file "$@" | sed 's/: .*, / /'
}

image_list() {
    for i; do
        echo "<p>$(name_and_size "$i" | html-escape)<br><img src='$i'>"
    done
}

cat <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$# GIFs</title>
<meta name=viewport content='width=device-width'>
<style>
body { margin: 0; color: #9e9e9e; background: #c9c9c9; font-family: sans-serif; }
@media(min-width: 600px) { p { width: 600px; margin-left: auto; margin-right: auto; } }
img { width: 100%; object-fit: contain; }
</style>
</head>
<body>
EOF

image_list "$@"

cat <<EOF
</body>
</html>
EOF
