#!/usr/bin/perl -w

use Getopt::Std;

sub fisher_yates_shuffle {
    $i = @_;
    while ($i--) {
        my $j = int(rand($i+1));
        @_[$i,$j] = @_[$j,$i];
    }
    return @_;
}

getopts('1fd:', \%opts);

if ($opts{f}) { $/ = "\n%\n"; }
if ($opts{d}) { $/ = $opts{d}; }

if ($opts{1}) {
    while (<>) { $line = $_ if rand($.) < 1; } print $line;
} else {
    print fisher_yates_shuffle(<>);
}
