#!/bin/sh

interp="$(which "$1")" && shift
case "$interp" in
    /usr/local/bin/*) interp="/usr/bin/env $(basename "$interp")";;
esac

for i in "$@"; do
    if [ ! -e "$i" ]; then
        printf "#!$interp\n\n" > "$i"
        chmod +x "$i"
        test -t 0 && ${EDITOR:-vi} "$i"
    fi
done
