#!/bin/sh

state_file="$HOME/var/ssh/agent.sh"

agent_running() {
    kill -0 "$SSH_AGENT_PID" 2>/dev/null
}

echo_state() {
    echo "export SSH_AGENT_PID='$SSH_AGENT_PID'"
    echo "export SSH_AUTH_SOCK='$SSH_AUTH_SOCK'"
}

save_agent() {
    mkdir -p "$(dirname "$state_file")"
    echo_state > "$state_file"
}

identity_added() {
    ssh-add -l >/dev/null 2>&1
}

if agent_running; then
    save_agent > "$state_file"
else
    test -e "$state_file" && . "$state_file"
    if ! agent_running; then
        eval "$(ssh-agent)"
        save_agent > "$state_file"
    fi
fi

if ! identity_added; then
    ssh-add
fi

exec "$@"
