#!/bin/sh

VAR=$HOME/var/ssh

kill -0 $SSH_AGENT_PID || eval $(ssh-agent)

cat <<EOF >$VAR/agent.sh
export SSH_AUTH_SOCK=$SSH_AUTH_SOCK
export SSH_AGENT_PID=$SSH_AGENT_PID
EOF

cat <<EOF >$VAR/agent.csh
setenv SSH_AUTH_SOCK $SSH_AUTH_SOCK
setenv SSH_AGENT_PID $SSH_AGENT_PID
EOF

ssh-add
exec "$@"
