#!/usr/bin/ruby

require 'uri'

cols = 13
rows = 1
dx = 100
dy = 10

parts = URI::parse(ARGV.shift).host.split('.')
tld = parts.last(2).all? {|p| p.length <= 2 } ? 3 : 2
host = parts.last(tld).join('.')

mouse = `xdotool getmouselocation`
x, y = mouse.match(/x:(\d+) y:(\d+)/).captures.collect(&:to_i)
args = "-T #{host} -g #{cols}x#{rows}+#{x-dx}+#{y-dy} #{ARGV.join(' ')}"

passwd = `urxvt #{args} -e sh -c 'spwgen #{host} >&3' 3>&1`.strip()
exec 'xdotool', 'type', passwd
